[package]
authors = [
    "Bodil Stokke <bodil@bodil.org>",
    "Jo Liss <joliss42@gmail.com>",
]
name = "pm"
version = "0.0.0"

[[bin]]
name = "pm"
path = "src/main.rs"

[dependencies]
colored = "1.5.3"
data-encoding = "2.0.0-rc.1"
docopt = "0.8"
futures = "0.1.14"
hyper = "0.11"
im = "7.0"
pest = "1.0.0-beta.11"
pest_derive = "1.0.0-beta.11"
quick-error = "1.2"
rand = "0.3"
reqwest = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
term_size = "0.3.0"
toml = "0.4"
url = "1.5"
webbrowser = "0.2"

[dependencies.pm_lib]
path = "../lib"
