[package]
authors = [
    "Bodil Stokke <bodil@bodil.org>",
    "Jo Liss <joliss42@gmail.com>",
]
name = "pm"
version = "0.0.0"

[[bin]]
name = "pm"
path = "src/main.rs"

[dependencies]
brotli = "1.0.8"
colored = "1.5.3"
data-encoding = "2.0.0-rc.1"
docopt = "0.8"
futures = "0.1.14"
glob = "0.2.11"
hyper = "0.11"
im = "7.0"
pest = "1.0.0-beta.11"
pest_derive = "1.0.0-beta.11"
quick-error = "1.2"
rand = "0.3"
reqwest = "0.7"
rmp-serde = "0.13.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.13"
term_size = "0.3.0"
toml = "0.4"
url = "1.5"
webbrowser = "0.2"

[dependencies.git2]
default-features = false
version = "0.6.8"

[dependencies.pm_lib]
path = "../lib"
