[package]
authors = ["Bodil Stokke <bodil@bodil.org>", "Jo Liss <joliss42@gmail.com>"]
name = "pm"
version = "0.0.0"

[[bin]]
name = "pm"
path = "src/main.rs"

[dependencies]
pm_lib = { path = "../lib" }
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
im = "5.0"
quick-error = "1.2"
toml = "0.4"
reqwest = "0.7"
linefeed = "0.2"
rpassword = "0.4"
