language: rust
rust:
  # remember to edit ./rust-toolchain as well
  - nightly
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  - DATABASE_URL="postgres://postgres@localhost/registry"
before_script:
  - psql -c 'create database registry;' -U postgres
  - cargo install diesel_cli --no-default-features --features postgres
script:
  - cd server; diesel database reset
  - cargo test --all && cargo test --all -- --ignored
