[package]
authors = ["Bodil Stokke <bodil@bodil.org>"]
name = "package-manager"
version = "1.0.0"

[lib]
name = "package_manager"
path = "src/core/lib.rs"

[[bin]]
name = "pm"
path = "src/bin/main.rs"

[dependencies]
docopt = "0.7"
toml = "0.3.0"
rustc-serialize = "0.3"
serde = "0.9.8"
serde_derive = "0.9.8"
serde_json = "0.9.8"
