[package]
authors = ["Bodil Stokke <bodil@bodil.org>", "Jo Liss <joliss42@gmail.com>"]
name = "pm_server"
version = "0.0.0"
[dependencies]
data-encoding = "2.0.0-rc.1"
diesel = { version = "0.15.2", features = ["postgres"] }
diesel_codegen = { version = "0.15.0", features = ["postgres"] }
dotenv = "0.10.1"
quick-error = "1.2"
rand = "0.3"
reqwest = "0.7"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.5.1"

[dependencies.im]
features = ["serde"]
version = "6.0"

[dependencies.maud]
features = ["rocket"]
version = "0.17"
