[package]
authors = [
    "Bodil Stokke <bodil@bodil.org>",
    "Jo Liss <joliss42@gmail.com>",
]
name = "pm_server"
version = "0.0.0"

[dependencies]
brotli = "1.0.8"
data-encoding = "2.0.0-rc.2"
dotenv = "0.10.1"
quick-error = "1.2"
reqwest = "0.7"
rmp-serde = "0.13.7"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.13"
url = "1.5.1"

[dependencies.diesel]
features = [
    "postgres",
    "large-tables",
]
version = "0.16"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.16"

[dependencies.im]
features = ["serde"]
version = "7.0"

[dependencies.pm_lib]
path = "../lib"
